services:
  - type: web
    name: stock-price-predictor
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --workers 1 --threads 4 --timeout 120 --keep-alive 5 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_DIR
        value: /tmp
      - key: PYTHON_VERSION
        value: 3.11.9
